spring:
  application:
    name: agromachinery-scraping

scraper:
  user-agent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36"
  timeout: 10000
  threads-count: 3
  await-termination-seconds: 30
  urls:
    https://www.agrofy.com.br/trator-magnum-315.html,
    https://www.agrofy.com.br/trator-john-deere-8320r-204540.html,
    https://www.tratoresecolheitadeiras.com.br/veiculo/uberlandia/mg/plataforma-colheitadeira/gts/flexer-xs-45/2023/45-pes/draper/triamaq-tratores/1028839,
    https://www.tratoresecolheitadeiras.com.br/veiculo/fernandopolis/sp/colheitadeira/john-deere/john-deere-s550/2022/-rotor-axial/cabine-cabinado/agro-novaes-maquinas-agricolas/1279673,
    https://www.mercadomaquinas.com.br/anuncio/247160-kombi-2013-2014-2013-franco-da-rocha-sp,
    https://www.mercadomaquinas.com.br/anuncio/236623-mini-escavadeira-bobcat-e27z-2019-sete-lagoas-mg